add_executable(simple src/sample/simple/simple.cpp)
add_executable(tuple src/sample/simple/tuple.cpp)
add_executable(template_retrieve src/sample/simple/template_retrieve.cpp)
add_executable(parameter_pack src/sample/simple/parameter_pack.cpp)
add_executable(template_class src/sample/simple/template_class.cpp)